/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AppTodos {
        "filter": string;
    }
    interface EditTodo {
        "editingIndex": number;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTodosElement extends Components.AppTodos, HTMLStencilElement {
    }
    var HTMLAppTodosElement: {
        prototype: HTMLAppTodosElement;
        new (): HTMLAppTodosElement;
    };
    interface HTMLEditTodoElement extends Components.EditTodo, HTMLStencilElement {
    }
    var HTMLEditTodoElement: {
        prototype: HTMLEditTodoElement;
        new (): HTMLEditTodoElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-todos": HTMLAppTodosElement;
        "edit-todo": HTMLEditTodoElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppTodos {
        "filter"?: string;
        "onEditItem"?: (event: CustomEvent<number>) => void;
    }
    interface EditTodo {
        "editingIndex"?: number;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-todos": AppTodos;
        "edit-todo": EditTodo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-todos": LocalJSX.AppTodos & JSXBase.HTMLAttributes<HTMLAppTodosElement>;
            "edit-todo": LocalJSX.EditTodo & JSXBase.HTMLAttributes<HTMLEditTodoElement>;
        }
    }
}
